dictionaryDefinitions:
  - name: unitsEn
    path: ./cspell/unitsEn.txt
  - name: unitsEnGb
    path: ./cspell/unitsEnGb.txt
dictionaries:
  - typescript
  - unitsEnGb
language: en-gb
words:
  - APIPA
  - aton
  - AVAHI
  - Bonjour
  - camelcase
  - dedupe
  - extinguishant
  - fsnip
  - GNSS
  - HMAC
  - jmespath
  - lcov
  - mdprepare
  - miscompare
  - mmsi
  - Mosquitto
  - NMEA
  - ortac
  - OWFS
  - powertrain
  - RAIM
  - tsdoc
  - volvo
  - waterjet
  - yanmar
ignorePaths:
  - package*.json
  - "*config*.*{json,js,yaml,yml}"
  - "*conf.*{json,js,yaml,yml}"
  - .git/**
  - .github/**
  - .vscode/**
  - .coveralls.yml
  - .*rc
  - "**.tgz"
ignoreRegExpList:
  - Urls
  - HexValues
  - Base64
  - Email
useGitignore: true
